trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: gitversion/setup@0
  displayName: 'Install GitVersion'
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: 'Get version information'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) -p:ContinuousIntegrationBuild=true'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: 'pack'
    nobuild: true
    packagesToPack: 'WordsToNumbers\WordsToNumbers.csproj'
    arguments: '-p:PackageVersion=$(GitVersion.NuGetPackageVersion)'

- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'